export const GET_CARDS = "GET_CARDS";
export const DELETE_CARD = "DELETE_CARD";
export const ADD_CARD = "ADD_CARD";

export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const ADD_COLLECTION = "ADD_COLLECTION";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_CARDS_LOADING = "GET_CARDS_LOADING";

export const EDIT_CARD = "EDIT_CARD";