# Generated by Django 3.0.4 on 2020-03-17 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
    ]
